version: "3.7"
services:
  bot:
    build: .
    container_name: reverso-context-bot
    restart: always
    environment:
      - DB_HOST=db

  db:
    image: postgres
    container_name: reverso-context-db
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=core
    ports:
      - 5432:5432
